

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
        
  h2:
    console:
      enabled: true
      path: /h2-console
      
server:
  port: 8080

logging:
  level:
    root: debug

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  config-location: classpath:/mybatis-config.xml